service: project3-pract-day3-2
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  
functions:
  status:
    handler: handler.handler
    events:
      - httpApi: 
          method: post
          path: /send
          
plugins:
  - serverless-lift
